
project_id = "mapjrbfzurpjmianfnev"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[functions]
[functions.generate-demand-content]
verify_jwt = true
