// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axnxfhxtnuhapcorkivy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4bnhmaHh0bnVoYXBjb3JraXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzMyMDUsImV4cCI6MjA1OTcwOTIwNX0.1-6EaHZfku0Mq1ATFq19-9G4hMian2BvQbNqxUgIFSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);