
import React from 'react';
import { ActionCardItem } from '@/types/dashboard';
import { 
  ClipboardList, MessageSquareReply, FileCheck, 
  BarChart2, PlusCircle, Search, Clock, 
  AlertTriangle, CheckCircle, FileText, ListFilter,
  ListTodo, FilePlus, UserCircle, Building,
  Trophy, MessageCircle
} from 'lucide-react';

// Helper function to get the Icon component from ID
export const getIconComponentFromId = (iconId: string) => {
  const iconMap: Record<string, React.ComponentType<any>> = {
    'clipboard-list': ClipboardList,
    'message-square-reply': MessageSquareReply,
    'file-check': FileCheck,
    'bar-chart-2': BarChart2,
    'plus-circle': PlusCircle,
    'search': Search,
    'clock': Clock,
    'alert-triangle': AlertTriangle,
    'check-circle': CheckCircle,
    'file-text': FileText,
    'list-filter': ListFilter,
    'list-todo': ListTodo,
    'file-plus': FilePlus,
    'user-circle': UserCircle,
    'building': Building,
    'trophy': Trophy,
    'message-circle': MessageCircle,
  };
  
  return iconMap[iconId] || ClipboardList;
};

// Generate default cards for the dashboard
export const getDefaultCards = (): ActionCardItem[] => {
  return [
    {
      id: 'smart-search',
      title: 'O que vamos fazer?',
      subtitle: 'Faça uma busca rápida',
      iconId: 'search',
      path: '',
      color: 'blue-light',
      width: '100',
      height: '1',
      type: 'smart_search',
      displayMobile: true,
      mobileOrder: 0,
    },
    {
      id: 'pending-tasks',
      title: 'Pendências e Prazos',
      subtitle: 'Visualize demandas e notas pendentes',
      iconId: 'list-todo',
      path: '/dashboard/comunicacao/demandas',
      color: 'blue-dark',
      width: '50',
      height: '2',
      type: 'special',
      isPendingActions: true,
      displayMobile: true,
      mobileOrder: 1,
    },
    {
      id: 'demandas',
      title: 'Demandas',
      subtitle: 'Gerenciar solicitações',
      iconId: 'clipboard-list',
      path: '/dashboard/comunicacao/demandas',
      color: 'blue-vivid',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 2,
    },
    {
      id: 'respostas',
      title: 'Responder Demandas',
      subtitle: 'Enviar respostas',
      iconId: 'message-square-reply',
      path: '/dashboard/comunicacao/responder-demanda',
      color: 'green-dark',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 3,
    },
    {
      id: 'notas',
      title: 'Notas Oficiais',
      subtitle: 'Gerenciar notas',
      iconId: 'file-check',
      path: '/dashboard/comunicacao/notas',
      color: 'orange-dark',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 4,
    },
    {
      id: 'relatorios',
      title: 'Relatórios',
      subtitle: 'Visualizar dados',
      iconId: 'bar-chart-2',
      path: '/dashboard/relatorios',
      color: 'deep-blue',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 5,
    },
    {
      id: 'quick-demand',
      title: 'Nova Demanda',
      subtitle: 'Criar demanda rápida',
      iconId: 'plus-circle',
      path: '/dashboard/comunicacao/cadastrar-demanda',
      color: 'green-neon',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 6,
    },
    {
      id: 'overdue-demands',
      title: 'Demandas Atrasadas',
      subtitle: 'Visualize prazos',
      iconId: 'alert-triangle',
      path: '/dashboard/comunicacao/demandas',
      color: 'orange-700',
      width: '25',
      height: '1',
      type: 'special',
      isOverdueDemands: true,
      displayMobile: true,
      mobileOrder: 7,
    },
    {
      id: 'criar-nota',
      title: 'Criar Nota',
      subtitle: 'Elabore notas oficiais',
      iconId: 'file-text',
      path: '/dashboard/comunicacao/criar-nota',
      color: 'blue-vivid',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 8,
    },
    {
      id: 'aprovar-notas',
      title: 'Aprovar Notas',
      subtitle: 'Revise e aprove notas',
      iconId: 'check-circle',
      path: '/dashboard/comunicacao/aprovar-nota',
      color: 'neutral-800',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 9,
    },
    {
      id: 'ranking',
      title: 'Ranking da Zeladoria',
      subtitle: 'Desempenho por região',
      iconId: 'trophy',
      path: '/dashboard/zeladoria/ranking-subs',
      color: 'green-dark',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 10,
    },
    {
      id: 'esic',
      title: 'e-SIC',
      subtitle: 'Acesso à informação',
      iconId: 'file-text',
      path: '/dashboard/esic',
      color: 'blue-light',
      width: '25',
      height: '1',
      type: 'standard',
      displayMobile: true,
      mobileOrder: 11,
    },
    {
      id: 'origin-selection',
      title: 'Cadastro de Demandas',
      subtitle: 'De onde vem a solicitação?',
      iconId: 'file-plus',
      path: '',
      color: 'blue-vivid',
      width: '50',
      height: '2',
      type: 'origin_selection',
      displayMobile: true,
      mobileOrder: 12,
    }
  ];
};

// Add the missing function that returns the communication-specific cards
export const getCommunicationActionCards = (): ActionCardItem[] => {
  return getDefaultCards().filter(card => 
    // Include all cards for communication department
    // We can exclude cards by ID if needed in the future
    !['hidden-card-for-other-departments'].includes(card.id)
  );
};
